### ISSUE TITLE
624rs bearing = 624-2rs?

### ISSUE THREAD

**Issue by tempestnano** [mjrice/Wilson2#14]
Should the bearing listed in the BOM as 624rs be 624-2RS? I was unable to find just a 624rs that wasn't just a cross-listed 624-2rs.

**Comment by hasbridge** [comment]
I noticed the same thing, only the bearings I found are listed as 624ZZ. I think probably any "624" sized bearing would work.

**Comment by mjrice** [comment]
@hasbridge is correct, any 624 bearing will work.
