### ISSUE TITLE
Im2596-mount.stl

### ISSUE THREAD

**Issue by feenix3k** [mjrice/Wilson2#16]
I tried to open the Im2596-mount.stl and got a error on the file. Slicer has been trying to repair it, but half of the image is missing when slic3r opens it to do repair.

**Comment by ArunKalahasti** [comment]
I opened without a problem for me in both Cura and KISSlicer. Perhaps it's an issue with your downloaded copy or with slic3r. Try opening it with one of those programs if you can have them slice the model for you
