### ISSUE TITLE
Lead screw length is not a formula in the BOM

### ISSUE THREAD

**Issue by elijahsgh** [mjrice/Wilson2#21]
I built to 400mm and seem to be needing 385mm lead screws.

Is Z height - 15mm a sane value for NEMA 17 with a coupler?

**Comment by hasbridge** [comment]
My leadscrews (300mm) are about 20mm off the top of the motor mount - they don't need to go all the way down.

**Comment by elijahsgh** [comment]
You mean all the way down in the z-coupler?  Yea, I shoved mine all the way down.  I'd still end up with a pretty big gap even if they were only just within the binding screw of the coupler.

What should the formula be?  Z - 15?  Z - 20?

**Comment by hasbridge** [comment]
I am confused - are you saying your vertical extrusions are 400mm tall, or 400mm build height? For 400mm long extrusions (what I used), then 300 is the correct length for the lead screws. I would think the formula would always be Z - 100, with Z representing the total vertical extrusion length.

**Comment by elijahsgh** [comment]
Z rod: 400mm
Z axis extrusions (vertical frame piece in sheet): 480mm
Z Print height: 280mm

My lead screws are 350mm and 35mm away from the top of the bearing trap - so that would mean I need 385mm lead screws to be perfectly level with the top of the bearing trap.  480mm - 100mm sounds good - that would put me at 380mm which should fit in the bearing trap.

Should we get a note or a formula cell added to the sheet for Z axis extrusion - 100 = lead screw length?

Cell C19 would be =(C11-100) ? \* Note that this would need the metric assist and is only an example.

**Comment by hasbridge** [comment]
Yeah, I think that should work out correct. There should be a slight gap between the leadscrew and motor shaft inside the coupler, so that would account for the extra 5mm.

**Comment by elijahsgh** [comment]
https://github.com/mjrice/Wilson2/pull/23

E19 (lead screw length) updated to =C$11-(IF(B$3="metric",100,4)) where C11 is "Vertical frame piece" extrusion.

**Comment by elijahsgh** [comment]
Marty did it a bit more gracefully. ;)

https://github.com/mjrice/Wilson2/commit/cf690a2f3e09eeb61adfe3a06d8e54011543dffe
