### ISSUE TITLE
Loose fitting x pieces

### ISSUE THREAD

**Issue by tbd-develop** [mjrice/Wilson2#30]
I've printed the x end-stops and when I go to put the bearings in there they are extremely loose. The x-carriage printed with the same settings, the same bearings are tight so I don't understand what I'm doing wrongly. I am printing at 25% infill with a .15 layer height, 4 top/bottom layers and 3 perimeters.

**Comment by ShRTee** [comment]
I did mine an they were fine, but now i have done these: http://www.thingiverse.com/thing:1201566
It seems that the bearings and the rods are loose, thay are not as tight as the original parts.
What am i doing wrong ??
printing in a Wanhao 4S with 3 laysers shell and 50 % infill.
Done them twice now, but same result
