### ISSUE TITLE
Coupler 5x8 removed?

### ISSUE THREAD

**Issue by damccull** [mjrice/Wilson2#35]
In commit 7a973b5f5a37ae7db1a1cd6b9108b6ed6812ef87 the coupler-5x8.stl file was removed. Is this intentional, and would I need this file in order to build the Wilson II?

**Comment by timmit99** [comment]
I built my Wilson II a while back and have just been using a spiral cut shaft coupler like [this](https://www.amazon.com/OctagonStar-Flexible-Couplings-Printer-Machine-2PCS/dp/B01HBPHSII/ref=sr_1_4?s=industrial&ie=UTF8&qid=1489674568&sr=1-4&keywords=5mm+to+8mm+coupler) They have worked great for my Wilson II as it is the workhorse of my 4 printers right now.
